name: build

on:
    workflow_dispatch:

jobs:
    setup:
        runs-on: ubuntu-20.04
        steps:
            -   name: Install dependencies
                run: sudo apt-get install -y nsis

            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Build setup
                run: |
                    bash build_nsis.sh

            -   uses: actions/upload-artifact@v4
                with:
                    path: build/*.exe
