name: release

on:
    create:
        tags:

jobs:
    setup:
        runs-on: ubuntu-20.04
        steps:
            -   name: Install dependencies
                run: sudo apt-get install -y nsis

            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Build project
                run: |
                    bash build_nsis.sh

            -   name: Upload Release Asset
                id: upload-release-asset
                uses: meeDamian/github-release@2.0
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    allow_override: true
                    gzip: false
                    body: >
                        appleJuice setup
                    files: >
                        build/
